# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9b974847dc7dd7a276c417a2d976a7bcf72ac53891ac0fb3f9892eda5953ff03a9343d2e7566999332abd24d9c1f14598e60a647cfec7351cd7718809a5e993e

test:
  secret_key_base: be01a3c4d87524e39a6a1066d5c400f002a519a8a38f29812ab5ef3729a4cf8685571da32f69c4efa356650c0254431caabbc7a574a15f5f419055e9e97e1cbb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
